cc_binary(
    name = 'rnnlm',
    srcs = [
        'rnnlm.cc',
    ],
    deps = [
        '//app/rnn:rnnbase'
    ],
)

#cc_binary(
#    name = 'test_rnnlm',
#    srcs = [
#        'rnnlm_test.cc',
#    ],
#    deps = [
#        '//app/rnn:rnnbase'
#    ],
#)
