cc_library(
    name = 'rnnbase',
    srcs = [
        'words.cc',
        'nce.cc',
        'nnet.cc',
        'maxent.cc',
        'hierarchical_softmax.cc',
    ],
    deps = [
        '//app/rnn/layers:layers',
    ],
)
