#cc_library(
#    name = [],
#    srcs = [],
#    deps = [],,,
#)
cc_library(
    name = 'layers',
    srcs = [
        'interface.cc',
        'layer_stack.cc',
        'simple_layer.cc',
        'gru_layer.cc',
        'scrn_layer.cc',
    ]
    #deps = [],
)

